FROM apache/airflow:3.1.6-python3.11

USER root
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3-dev \
        gcc \
        g++ \
        libgomp1 \
        libopenblas-dev \
        liblapack-dev \
        libatlas-base-dev \
        libboost-dev \
        libboost-system-dev \
        libboost-filesystem-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER airflow

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#COPY dags/ab_test_api.py .

#EXPOSE 5000

#CMD ["python", "ab_test_api.py"]